TYPE=VIEW
query=select `travelagency`.`hotel_clients`.`Name` AS `a`,`travelagency`.`hotel_clients`.`Family` AS `b`,`travelagency`.`flight_passengers`.`Name` AS `c`,`travelagency`.`flight_passengers`.`Family` AS `d`,`travelagency`.`hotels`.`name` AS `e`,`travelagency`.`hotels`.`category` AS `f`,`travelagency`.`flights`.`DestinationId` AS `g`,`travelagency`.`flights`.`DepartureId` AS `h`,`cities_destination`.`Name` AS `i`,`travelagency`.`airplane`.`Name` AS `j`,`travelagency`.`airplane`.`specificationId` AS `k`,`travelagency`.`aireplane_specifications`.`Type` AS `l`,`travelagency`.`aireplane_specifications`.`Name` AS `m`,`cities_departure`.`Name` AS `n`,`travelagency`.`airlines`.`Name` AS `o` from ((((((((`travelagency`.`airplane` join `travelagency`.`aireplane_specifications` on((`travelagency`.`airplane`.`specificationId` = `travelagency`.`aireplane_specifications`.`Id`))) join `travelagency`.`flights` on((`travelagency`.`flights`.`Id` = `travelagency`.`airplane`.`FlightId`))) join `travelagency`.`flight_passengers` on((`travelagency`.`flights`.`Id` = `travelagency`.`flight_passengers`.`FlightId`))) join `travelagency`.`cities` `cities_departure` on((`cities_departure`.`Id` = `travelagency`.`flights`.`DepartureId`))) join `travelagency`.`cities` `cities_destination` on((`cities_destination`.`Id` = `travelagency`.`flights`.`DestinationId`))) join `travelagency`.`hotels` on((`cities_destination`.`Id` = `travelagency`.`hotels`.`CityId`))) join `travelagency`.`hotel_clients` on((`travelagency`.`hotels`.`ID` = `travelagency`.`hotel_clients`.`HotelId`))) join `travelagency`.`airlines` on((`travelagency`.`airplane`.`AirlineName` = `travelagency`.`airlines`.`Name`)))
md5=a011fb28fc39c00b838db5e9f1f0480c
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2012-12-18 00:36:48
create-version=1
source=SELECT hotel_clients.Name AS a\n	     , hotel_clients.Family AS b\n	     , flight_passengers.Name AS c\n	     , flight_passengers.Family AS d\n	     , hotels.name AS e\n	     , hotels.category AS f\n	     , flights.DestinationId AS g\n	     , flights.DepartureId AS h\n	     , cities_destination.Name AS i\n	     , airplane.Name AS j\n	     , airplane.specificationId AS k\n	     , aireplane_specifications.Type AS l\n	     , aireplane_specifications.Name AS m\n	     , cities_departure.Name AS n\n	     , airlines.Name as o\n	FROM\n	  airplane\n	INNER JOIN aireplane_specifications\n	ON airplane.specificationId = aireplane_specifications.Id\n	INNER JOIN flights\n	ON flights.Id = airplane.FlightId\n	INNER JOIN flight_passengers\n	ON flights.Id = flight_passengers.FlightId\n	INNER JOIN cities cities_departure\n	ON cities_departure.Id = flights.DepartureId\n	INNER JOIN cities cities_destination\n	ON cities_destination.Id = flights.DestinationId\n	INNER JOIN hotels\n	ON cities_destination.Id = hotels.CityId\n	INNER JOIN hotel_clients\n	ON hotels.ID = hotel_clients.HotelId\n	INNER JOIN airlines\n	ON airplane.AirlineName = airlines.Name
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `travelagency`.`hotel_clients`.`Name` AS `a`,`travelagency`.`hotel_clients`.`Family` AS `b`,`travelagency`.`flight_passengers`.`Name` AS `c`,`travelagency`.`flight_passengers`.`Family` AS `d`,`travelagency`.`hotels`.`name` AS `e`,`travelagency`.`hotels`.`category` AS `f`,`travelagency`.`flights`.`DestinationId` AS `g`,`travelagency`.`flights`.`DepartureId` AS `h`,`cities_destination`.`Name` AS `i`,`travelagency`.`airplane`.`Name` AS `j`,`travelagency`.`airplane`.`specificationId` AS `k`,`travelagency`.`aireplane_specifications`.`Type` AS `l`,`travelagency`.`aireplane_specifications`.`Name` AS `m`,`cities_departure`.`Name` AS `n`,`travelagency`.`airlines`.`Name` AS `o` from ((((((((`travelagency`.`airplane` join `travelagency`.`aireplane_specifications` on((`travelagency`.`airplane`.`specificationId` = `travelagency`.`aireplane_specifications`.`Id`))) join `travelagency`.`flights` on((`travelagency`.`flights`.`Id` = `travelagency`.`airplane`.`FlightId`))) join `travelagency`.`flight_passengers` on((`travelagency`.`flights`.`Id` = `travelagency`.`flight_passengers`.`FlightId`))) join `travelagency`.`cities` `cities_departure` on((`cities_departure`.`Id` = `travelagency`.`flights`.`DepartureId`))) join `travelagency`.`cities` `cities_destination` on((`cities_destination`.`Id` = `travelagency`.`flights`.`DestinationId`))) join `travelagency`.`hotels` on((`cities_destination`.`Id` = `travelagency`.`hotels`.`CityId`))) join `travelagency`.`hotel_clients` on((`travelagency`.`hotels`.`ID` = `travelagency`.`hotel_clients`.`HotelId`))) join `travelagency`.`airlines` on((`travelagency`.`airplane`.`AirlineName` = `travelagency`.`airlines`.`Name`)))
