-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/16/2012 3:06:40 PM
-- Server version: 5.5.16
-- Client version: 4.1

USE travelagency;

CREATE TABLE aireplane_specifications(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  Type VARCHAR(50) DEFAULT NULL,
  NoOfFirstClassSeats INT(11) DEFAULT NULL,
  NoOfBusinessClassSeats INT(11) DEFAULT NULL,
  NoOfEconomyClassSeats INT(11) DEFAULT NULL,
  PriceOfFirstClassSeats INT(11) DEFAULT NULL,
  PriceOfBusinessClassSeats INT(11) DEFAULT NULL,
  PriceOfEconomyClassSeats INT(11) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flight_passengers(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  PassportExpirey TIMESTAMP NULL DEFAULT NULL,
  Nationality VARCHAR(50) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  FlightId INT(11) DEFAULT NULL,
  SeatId VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX FlightId (FlightId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE hotel_clients(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  RoomId VARCHAR(20) DEFAULT NULL,
  HotelId INT(11) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX HotelId (HotelId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE users(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  Username VARCHAR(50) DEFAULT NULL,
  Passoword VARCHAR(100) DEFAULT NULL,
  CreditCradType VARCHAR(20) DEFAULT NULL,
  CreditCardNumber VARCHAR(100) DEFAULT NULL,
  CreditCardSecurityNumber VARBINARY(100) DEFAULT NULL,
  PassportExpiry DATETIME DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airplane(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  specificationId INT(11) DEFAULT NULL,
  FlightId INT(11) DEFAULT NULL,
  `Date` DATETIME DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX FlightId (FlightId),
  CONSTRAINT FK_airplane_aireplane_specifications_Id FOREIGN KEY (specificationId)
  REFERENCES aireplane_specifications (Id) ON DELETE NO ACTION ON UPDATE NO ACTION
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE hotels(
  ID INT(11) NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  category INT(11) DEFAULT NULL,
  price_per_day DECIMAL(10, 0) DEFAULT NULL,
  CityId INT(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX CityId (CityId),
  CONSTRAINT FK_hotels_hotel_clients_HotelId FOREIGN KEY (ID)
  REFERENCES hotel_clients (HotelId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flightes(
  Id INT(11) NOT NULL,
  DestinationId INT(11) DEFAULT NULL,
  DepartureId INT(11) DEFAULT NULL,
  FlightNumber VARCHAR(50) DEFAULT NULL,
  AirlineName VARCHAR(50) DEFAULT NULL,
  FlightDate DATETIME DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX DepartureId (DepartureId),
  UNIQUE INDEX DestinationId (DestinationId),
  CONSTRAINT FK_flightes_airplane_FlightId FOREIGN KEY (Id)
  REFERENCES airplane (FlightId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_flightes_flight_passengers_FlightId FOREIGN KEY (Id)
  REFERENCES flight_passengers (FlightId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE cities(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_cities_flightes_DepartureId FOREIGN KEY (Id)
  REFERENCES flightes (DepartureId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_cities_flightes_DestinationId FOREIGN KEY (Id)
  REFERENCES flightes (DestinationId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_cities_hotels_CityId FOREIGN KEY (Id)
  REFERENCES hotels (CityId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;