-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/18/2012 12:46:10 AM
-- Server version: 5.5.16
-- Client version: 4.1

USE travelagency;

CREATE TABLE aireplane_specifications(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Type VARCHAR(50) DEFAULT NULL,
  NoOfFirstClassSeats INT(11) DEFAULT NULL,
  NoOfBusinessClassSeats INT(11) DEFAULT NULL,
  NoOfEconomyClassSeats INT(11) DEFAULT NULL,
  PriceOfFirstClassSeats INT(11) DEFAULT NULL,
  PriceOfBusinessClassSeats INT(11) DEFAULT NULL,
  PriceOfEconomyClassSeats INT(11) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airlines(
  Id INT(11) NOT NULL,
  Name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE users(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  Username VARCHAR(50) DEFAULT NULL,
  Passoword VARCHAR(100) DEFAULT NULL,
  CreditCradType VARCHAR(20) DEFAULT NULL,
  CreditCardNumber VARCHAR(100) DEFAULT NULL,
  CreditCardSecurityNumber VARBINARY(100) DEFAULT NULL,
  PassportExpiry DATETIME DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airplanes(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  specificationId INT(11) DEFAULT 0,
  FlightId INT(11) DEFAULT 0,
  `Date` DATETIME DEFAULT NULL,
  AirlineId INT(11) DEFAULT 0,
  PRIMARY KEY (Id),
  UNIQUE INDEX FlightId (FlightId),
  CONSTRAINT FK_airplanes_aireplane_specifications_Id FOREIGN KEY (specificationId)
  REFERENCES aireplane_specifications (Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_airplanes_airlines_Id FOREIGN KEY (AirlineId)
  REFERENCES airlines (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flights(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  DestinationId INT(11) DEFAULT 0,
  DepartureId INT(11) DEFAULT 0,
  FlightNumber VARCHAR(50) DEFAULT '0',
  AirplaneId INT(11) DEFAULT 0,
  TakeoffDate DATETIME DEFAULT NULL,
  LandingDate DATETIME DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX DepartureId (DepartureId),
  UNIQUE INDEX DestinationId (DestinationId),
  UNIQUE INDEX FlightNumber (FlightNumber),
  CONSTRAINT FK_flights_airplanes_Id FOREIGN KEY (AirplaneId)
  REFERENCES airplanes (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE cities(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  AirportName VARCHAR(100) DEFAULT NULL,
  AirportAddress VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_cities_flights_DepartureId FOREIGN KEY (Id)
  REFERENCES flights (DepartureId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_cities_flights_DestinationId FOREIGN KEY (Id)
  REFERENCES flights (DestinationId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flight_passengers(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  PassportExpirey TIMESTAMP NULL DEFAULT NULL,
  Nationality VARCHAR(50) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  FlightId INT(11) DEFAULT NULL,
  SeatId VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX FlightId (FlightId),
  CONSTRAINT FK_flight_passengers FOREIGN KEY (FlightId)
  REFERENCES flights (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE hotels(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  category INT(11) DEFAULT NULL,
  price_per_day DECIMAL(10, 0) DEFAULT NULL,
  CityId INT(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX CityId (CityId),
  CONSTRAINT FK_hotels_cities_Id FOREIGN KEY (CityId)
  REFERENCES cities (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE hotel_clients(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  RoomId VARCHAR(20) DEFAULT NULL,
  HotelId INT(11) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX HotelId (HotelId),
  CONSTRAINT FK_hotel_clients_hotels_ID FOREIGN KEY (HotelId)
  REFERENCES hotels (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW view2
AS
SELECT `travelagency`.`hotel_clients`.`Name` AS `a`
     , `travelagency`.`hotel_clients`.`Family` AS `b`
     , `travelagency`.`flight_passengers`.`Name` AS `c`
     , `travelagency`.`flight_passengers`.`Family` AS `d`
     , `travelagency`.`hotels`.`name` AS `e`
     , `travelagency`.`hotels`.`category` AS `f`
     , `travelagency`.`flights`.`DestinationId` AS `g`
     , `travelagency`.`flights`.`DepartureId` AS `h`
     , `cities_destination`.`Name` AS `i`
     , `travelagency`.`airplane`.`Name` AS `j`
     , `travelagency`.`airplane`.`specificationId` AS `k`
     , `travelagency`.`aireplane_specifications`.`Type` AS `l`
     , `travelagency`.`aireplane_specifications`.`Name` AS `m`
     , `cities_departure`.`Name` AS `n`
     , `travelagency`.`airlines`.`Name` AS `o`
FROM
  ((((((((`airplane`
JOIN `aireplane_specifications`
ON ((`travelagency`.`airplane`.`specificationId` = `travelagency`.`aireplane_specifications`.`Id`)))
JOIN `flights`
ON ((`travelagency`.`flights`.`Id` = `travelagency`.`airplane`.`FlightId`)))
JOIN `flight_passengers`
ON ((`travelagency`.`flights`.`Id` = `travelagency`.`flight_passengers`.`FlightId`)))
JOIN `cities` `cities_departure`
ON ((`cities_departure`.`Id` = `travelagency`.`flights`.`DepartureId`)))
JOIN `cities` `cities_destination`
ON ((`cities_destination`.`Id` = `travelagency`.`flights`.`DestinationId`)))
JOIN `hotels`
ON ((`cities_destination`.`Id` = `travelagency`.`hotels`.`CityId`)))
JOIN `hotel_clients`
ON ((`travelagency`.`hotels`.`ID` = `travelagency`.`hotel_clients`.`HotelId`)))
JOIN `airlines`
ON ((`travelagency`.`airplane`.`AirlineName` = `travelagency`.`airlines`.`Name`)));