-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/19/2012 10:47:20 PM
-- Server version: 5.5.16
-- Client version: 4.1

USE travelagency;

CREATE TABLE airlines(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) DEFAULT NULL,
  Country VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE authassignment(
  itemname VARCHAR(64) NOT NULL,
  userid VARCHAR(64) NOT NULL,
  bizrule TEXT DEFAULT NULL,
  `data` TEXT DEFAULT NULL,
  PRIMARY KEY (itemname, userid)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE authitem(
  name VARCHAR(64) NOT NULL,
  type INT(11) NOT NULL,
  description TEXT DEFAULT NULL,
  bizrule TEXT DEFAULT NULL,
  `data` TEXT DEFAULT NULL,
  PRIMARY KEY (name)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 963
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE authitemchild(
  parent VARCHAR(64) NOT NULL,
  child VARCHAR(64) NOT NULL,
  PRIMARY KEY (parent, child),
  INDEX child (child)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 862
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE cities(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE clients(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  RoomlId INT(11) DEFAULT NULL,
  CreditCardType VARCHAR(255) DEFAULT NULL,
  CreditCardExpiryDate VARCHAR(255) DEFAULT NULL,
  CreditCardHolderName VARCHAR(255) DEFAULT NULL,
  CreditCardSecurityNumber VARCHAR(255) DEFAULT NULL,
  CreditCardNumber VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE groups(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE operator_group(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  GroupId INT(11) DEFAULT 0,
  OperatorId INT(11) DEFAULT 0,
  PRIMARY KEY (Id),
  UNIQUE INDEX GroupId (GroupId),
  UNIQUE INDEX OperatorId (OperatorId)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE roles(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  groupId INT(11) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX groupId (groupId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE website_operators(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  Username VARCHAR(50) DEFAULT NULL,
  Passoword VARCHAR(100) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX email (email),
  UNIQUE INDEX Username (Username)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE website_users(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  Username VARCHAR(50) DEFAULT NULL,
  Passoword VARCHAR(100) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  CreditCradType VARCHAR(20) DEFAULT NULL,
  CreditCardNumber VARCHAR(100) DEFAULT NULL,
  CreditCardSecurityNumber VARCHAR(100) DEFAULT NULL,
  PassportExpiry DATETIME DEFAULT NULL,
  CreditCardExpiry VARCHAR(100) DEFAULT NULL,
  CreditCardHolderName VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX email (email),
  UNIQUE INDEX PassportNumber (PassportNumber),
  UNIQUE INDEX Username (Username)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airports(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) DEFAULT NULL,
  Address VARCHAR(255) DEFAULT NULL,
  CityId INT(11) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX CityId (CityId),
  CONSTRAINT FK_airports_cities_Id FOREIGN KEY (CityId)
  REFERENCES cities (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE hotels(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) DEFAULT NULL,
  Category INT(11) DEFAULT NULL,
  CityId INT(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_hotels_cities_Id FOREIGN KEY (CityId)
  REFERENCES cities (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 19
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flights(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  DepartureAirportId INT(11) DEFAULT NULL,
  DestinationAirportId INT(11) DEFAULT NULL,
  FlightNumber VARCHAR(50) DEFAULT NULL,
  AirplaneId INT(11) DEFAULT NULL,
  TakeoffDate DATETIME DEFAULT NULL,
  LandingDate DATETIME DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX DepartureId (DepartureAirportId),
  UNIQUE INDEX DestinationId (DestinationAirportId),
  INDEX FK_flights_airplanes_Id (AirplaneId),
  UNIQUE INDEX FlightNumber (FlightNumber),
  CONSTRAINT FK_flights_airports_Id FOREIGN KEY (DepartureAirportId)
  REFERENCES airports (Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_flights_airports_Id2 FOREIGN KEY (DestinationAirportId)
  REFERENCES airports (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE rooms(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  HotelId INT(11) DEFAULT NULL,
  RoomNumber VARCHAR(20) DEFAULT NULL,
  Capacity INT(11) DEFAULT NULL,
  Type VARCHAR(25) DEFAULT NULL,
  PricePerDay INT(11) DEFAULT NULL,
  Tell VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX HotelId (HotelId),
  UNIQUE INDEX RoomNumber (RoomNumber),
  CONSTRAINT FK_rooms_hotels_ID FOREIGN KEY (HotelId)
  REFERENCES hotels (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airplanes(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  FlightId INT(11) DEFAULT NULL,
  `Date` DATETIME DEFAULT NULL,
  AirlineId INT(11) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX AirlineId (AirlineId),
  UNIQUE INDEX FlightId (FlightId),
  CONSTRAINT FK_airplanes_airlines_Id FOREIGN KEY (AirlineId)
  REFERENCES airlines (Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_airplanes_flights_Id FOREIGN KEY (FlightId)
  REFERENCES flights (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flight_passengers(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  PassportExpirey TIMESTAMP NULL DEFAULT NULL,
  Nationality VARCHAR(50) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  FlightId INT(11) DEFAULT NULL,
  SeatId VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX FlightId (FlightId),
  CONSTRAINT FK_flight_passengers FOREIGN KEY (FlightId)
  REFERENCES flights (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE room_clients(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  RoomId INT(11) DEFAULT NULL,
  ClientId INT(11) DEFAULT NULL,
  StartDate DATETIME DEFAULT NULL,
  EndDate DATETIME DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX ClientId (ClientId),
  UNIQUE INDEX RoomId (RoomId),
  CONSTRAINT FK_room_clients_clients_Id FOREIGN KEY (ClientId)
  REFERENCES clients (Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_room_clients_rooms_Id FOREIGN KEY (RoomId)
  REFERENCES rooms (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE aireplane_specifications(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Type VARCHAR(50) DEFAULT NULL,
  NoOfFirstClassSeats INT(11) DEFAULT NULL,
  NoOfBusinessClassSeats INT(11) DEFAULT NULL,
  NoOfEconomyClassSeats INT(11) DEFAULT NULL,
  PriceOfFirstClassSeats INT(11) DEFAULT NULL,
  PriceOfBusinessClassSeats INT(11) DEFAULT NULL,
  PriceOfEconomyClassSeats INT(11) DEFAULT NULL,
  AirplaneId INT(11) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX AirplaneId (AirplaneId),
  CONSTRAINT FK_aireplane_specifications_airplanes_Id FOREIGN KEY (AirplaneId)
  REFERENCES airplanes (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW hotles_view
AS
SELECT `cities`.`Name` AS `CityName`
     , `hotels`.`ID` AS `ID`
     , `hotels`.`Name` AS `HotelName`
     , `hotels`.`Category` AS `Category`
FROM
  (`hotels`
JOIN `cities`
ON ((`hotels`.`CityId` = `cities`.`Id`)));

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW view2
AS
SELECT `travelagency`.`hotel_clients`.`Name` AS `a`
     , `travelagency`.`hotel_clients`.`Family` AS `b`
     , `travelagency`.`flight_passengers`.`Name` AS `c`
     , `travelagency`.`flight_passengers`.`Family` AS `d`
     , `travelagency`.`hotels`.`name` AS `e`
     , `travelagency`.`hotels`.`category` AS `f`
     , `travelagency`.`flights`.`DestinationId` AS `g`
     , `travelagency`.`flights`.`DepartureId` AS `h`
     , `cities_destination`.`Name` AS `i`
     , `travelagency`.`airplane`.`Name` AS `j`
     , `travelagency`.`airplane`.`specificationId` AS `k`
     , `travelagency`.`aireplane_specifications`.`Type` AS `l`
     , `travelagency`.`aireplane_specifications`.`Name` AS `m`
     , `cities_departure`.`Name` AS `n`
     , `travelagency`.`airlines`.`Name` AS `o`
FROM
  ((((((((`airplane`
JOIN `aireplane_specifications`
ON ((`travelagency`.`airplane`.`specificationId` = `travelagency`.`aireplane_specifications`.`Id`)))
JOIN `flights`
ON ((`travelagency`.`flights`.`Id` = `travelagency`.`airplane`.`FlightId`)))
JOIN `flight_passengers`
ON ((`travelagency`.`flights`.`Id` = `travelagency`.`flight_passengers`.`FlightId`)))
JOIN `cities` `cities_departure`
ON ((`cities_departure`.`Id` = `travelagency`.`flights`.`DepartureId`)))
JOIN `cities` `cities_destination`
ON ((`cities_destination`.`Id` = `travelagency`.`flights`.`DestinationId`)))
JOIN `hotels`
ON ((`cities_destination`.`Id` = `travelagency`.`hotels`.`CityId`)))
JOIN `hotel_clients`
ON ((`travelagency`.`hotels`.`ID` = `travelagency`.`hotel_clients`.`HotelId`)))
JOIN `airlines`
ON ((`travelagency`.`airplane`.`AirlineName` = `travelagency`.`airlines`.`Name`)));