-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/18/2012 1:34:00 AM
-- Server version: 5.5.16
-- Client version: 4.1

USE travelagency;

CREATE TABLE aireplane_specifications(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Type VARCHAR(50) DEFAULT NULL,
  NoOfFirstClassSeats INT(11) DEFAULT NULL,
  NoOfBusinessClassSeats INT(11) DEFAULT NULL,
  NoOfEconomyClassSeats INT(11) DEFAULT NULL,
  PriceOfFirstClassSeats INT(11) DEFAULT NULL,
  PriceOfBusinessClassSeats INT(11) DEFAULT NULL,
  PriceOfEconomyClassSeats INT(11) DEFAULT NULL,
  AirplaneId INT(11) DEFAULT 0,
  PRIMARY KEY (Id),
  UNIQUE INDEX AirplaneId (AirplaneId)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE cities(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 6
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flight_passengers(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  PassportExpirey TIMESTAMP NULL DEFAULT NULL,
  Nationality VARCHAR(50) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  FlightId INT(11) DEFAULT NULL,
  SeatId VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX FlightId (FlightId)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE users(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  Username VARCHAR(50) DEFAULT NULL,
  Passoword VARCHAR(100) DEFAULT NULL,
  CreditCradType VARCHAR(20) DEFAULT NULL,
  CreditCardNumber VARCHAR(100) DEFAULT NULL,
  CreditCardSecurityNumber VARBINARY(100) DEFAULT NULL,
  PassportExpiry DATETIME DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airplanes(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  FlightId INT(11) DEFAULT 0,
  `Date` DATETIME DEFAULT NULL,
  AirlineId INT(11) DEFAULT 0,
  PRIMARY KEY (Id),
  UNIQUE INDEX AirlineId (AirlineId),
  UNIQUE INDEX FlightId (FlightId),
  CONSTRAINT FK_airplanes_aireplane_specifications_AirplaneId FOREIGN KEY (Id)
  REFERENCES aireplane_specifications (AirplaneId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE hotels(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) DEFAULT NULL,
  Category INT(11) DEFAULT NULL,
  PricePerDay DECIMAL(10, 0) DEFAULT NULL,
  CityId INT(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX CityId (CityId),
  CONSTRAINT FK_hotels_cities_Id FOREIGN KEY (CityId)
  REFERENCES cities (Id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airlines(
  Id INT(11) NOT NULL,
  Name VARCHAR(255) DEFAULT NULL,
  Country VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_airlines_airplanes_AirlineId FOREIGN KEY (Id)
  REFERENCES airplanes (AirlineId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flights(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  DepartureAirportId INT(11) DEFAULT 0,
  DestinationAirportId INT(11) DEFAULT 0,
  FlightNumber VARCHAR(50) DEFAULT '0',
  AirplaneId INT(11) DEFAULT 0,
  TakeoffDate DATETIME DEFAULT NULL,
  LandingDate DATETIME DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX DepartureId (DepartureAirportId),
  UNIQUE INDEX DestinationId (DestinationAirportId),
  INDEX FK_flights_airplanes_Id (AirplaneId),
  UNIQUE INDEX FlightNumber (FlightNumber),
  CONSTRAINT FK_flights_airplanes_FlightId FOREIGN KEY (Id)
  REFERENCES airplanes (FlightId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_flights_flight_passengers_FlightId FOREIGN KEY (Id)
  REFERENCES flight_passengers (FlightId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE hotel_clients(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  RoomId VARCHAR(20) DEFAULT NULL,
  HotelId INT(11) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX HotelId (HotelId),
  CONSTRAINT FK_hotel_clients_hotels_ID FOREIGN KEY (HotelId)
  REFERENCES hotels (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airports(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) DEFAULT NULL,
  Address VARCHAR(255) DEFAULT NULL,
  CityId INT(11) DEFAULT 0,
  PRIMARY KEY (Id),
  UNIQUE INDEX CityId (CityId),
  CONSTRAINT FK_airports_cities_Id FOREIGN KEY (CityId)
  REFERENCES cities (Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_airports_flights_DepartureAirportId FOREIGN KEY (Id)
  REFERENCES flights (DepartureAirportId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_airports_flights_DestinationAirportId FOREIGN KEY (Id)
  REFERENCES flights (DestinationAirportId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
AUTO_INCREMENT = 3
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW view2
AS
SELECT `travelagency`.`hotel_clients`.`Name` AS `a`
     , `travelagency`.`hotel_clients`.`Family` AS `b`
     , `travelagency`.`flight_passengers`.`Name` AS `c`
     , `travelagency`.`flight_passengers`.`Family` AS `d`
     , `travelagency`.`hotels`.`name` AS `e`
     , `travelagency`.`hotels`.`category` AS `f`
     , `travelagency`.`flights`.`DestinationId` AS `g`
     , `travelagency`.`flights`.`DepartureId` AS `h`
     , `cities_destination`.`Name` AS `i`
     , `travelagency`.`airplane`.`Name` AS `j`
     , `travelagency`.`airplane`.`specificationId` AS `k`
     , `travelagency`.`aireplane_specifications`.`Type` AS `l`
     , `travelagency`.`aireplane_specifications`.`Name` AS `m`
     , `cities_departure`.`Name` AS `n`
     , `travelagency`.`airlines`.`Name` AS `o`
FROM
  ((((((((`airplane`
JOIN `aireplane_specifications`
ON ((`travelagency`.`airplane`.`specificationId` = `travelagency`.`aireplane_specifications`.`Id`)))
JOIN `flights`
ON ((`travelagency`.`flights`.`Id` = `travelagency`.`airplane`.`FlightId`)))
JOIN `flight_passengers`
ON ((`travelagency`.`flights`.`Id` = `travelagency`.`flight_passengers`.`FlightId`)))
JOIN `cities` `cities_departure`
ON ((`cities_departure`.`Id` = `travelagency`.`flights`.`DepartureId`)))
JOIN `cities` `cities_destination`
ON ((`cities_destination`.`Id` = `travelagency`.`flights`.`DestinationId`)))
JOIN `hotels`
ON ((`cities_destination`.`Id` = `travelagency`.`hotels`.`CityId`)))
JOIN `hotel_clients`
ON ((`travelagency`.`hotels`.`ID` = `travelagency`.`hotel_clients`.`HotelId`)))
JOIN `airlines`
ON ((`travelagency`.`airplane`.`AirlineName` = `travelagency`.`airlines`.`Name`)));