-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/17/2012 7:37:08 PM
-- Server version: 5.5.16
-- Client version: 4.1

USE travelagency;

CREATE TABLE aireplane_specifications(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Type VARCHAR(50) DEFAULT NULL,
  NoOfFirstClassSeats INT(11) DEFAULT NULL,
  NoOfBusinessClassSeats INT(11) DEFAULT NULL,
  NoOfEconomyClassSeats INT(11) DEFAULT NULL,
  PriceOfFirstClassSeats INT(11) DEFAULT NULL,
  PriceOfBusinessClassSeats INT(11) DEFAULT NULL,
  PriceOfEconomyClassSeats INT(11) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airlines(
  Id INT(11) NOT NULL,
  Name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE airplane(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  specificationId INT(11) DEFAULT NULL,
  FlightId INT(11) DEFAULT NULL,
  `Date` DATETIME DEFAULT NULL,
  AirlineName VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX FlightId (FlightId)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE cities(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flight_passengers(
  Id INT(11) NOT NULL,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  PassportExpirey TIMESTAMP NULL DEFAULT NULL,
  Nationality VARCHAR(50) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  FlightId INT(11) DEFAULT NULL,
  SeatId VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX FlightId (FlightId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE flights(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  DestinationId INT(11) DEFAULT NULL,
  DepartureId INT(11) DEFAULT NULL,
  FlightNumber VARCHAR(50) DEFAULT NULL,
  AirlineName VARCHAR(50) DEFAULT NULL,
  FlightDate DATETIME DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX DepartureId (DepartureId),
  UNIQUE INDEX DestinationId (DestinationId)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE hotel_clients(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  RoomId VARCHAR(20) DEFAULT NULL,
  HotelId INT(11) DEFAULT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX HotelId (HotelId)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE hotels(
  ID INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  category INT(11) DEFAULT NULL,
  price_per_day DECIMAL(10, 0) DEFAULT NULL,
  CityId INT(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX CityId (CityId)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE users(
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) DEFAULT NULL,
  Family VARCHAR(70) DEFAULT NULL,
  Tell VARCHAR(20) DEFAULT NULL,
  PassportNumber VARCHAR(50) DEFAULT NULL,
  Address VARCHAR(200) DEFAULT NULL,
  Username VARCHAR(50) DEFAULT NULL,
  Passoword VARCHAR(100) DEFAULT NULL,
  CreditCradType VARCHAR(20) DEFAULT NULL,
  CreditCardNumber VARCHAR(100) DEFAULT NULL,
  CreditCardSecurityNumber VARBINARY(100) DEFAULT NULL,
  PassportExpiry DATETIME DEFAULT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE OR REPLACE
DEFINER = 'root'@'localhost'
VIEW view2
AS
SELECT `hotel_clients`.`Name` AS `a`
     , `hotel_clients`.`Family` AS `b`
     , `flight_passengers`.`Name` AS `c`
     , `flight_passengers`.`Family` AS `d`
     , `hotels`.`name` AS `e`
     , `hotels`.`category` AS `f`
     , `flights`.`DestinationId` AS `g`
     , `flights`.`DepartureId` AS `h`
     , `cities_destination`.`Name` AS `i`
     , `airplane`.`Name` AS `j`
     , `airplane`.`specificationId` AS `k`
     , `aireplane_specifications`.`Type` AS `l`
     , `aireplane_specifications`.`Name` AS `m`
     , `cities_departure`.`Name` AS `n`
     , `airlines`.`Name` AS `o`
FROM
  ((((((((`airplane`
JOIN `aireplane_specifications`
ON ((`airplane`.`specificationId` = `aireplane_specifications`.`Id`)))
JOIN `flights`
ON ((`flights`.`Id` = `airplane`.`FlightId`)))
JOIN `flight_passengers`
ON ((`flights`.`Id` = `flight_passengers`.`FlightId`)))
JOIN `cities` `cities_departure`
ON ((`cities_departure`.`Id` = `flights`.`DepartureId`)))
JOIN `cities` `cities_destination`
ON ((`cities_destination`.`Id` = `flights`.`DestinationId`)))
JOIN `hotels`
ON ((`cities_destination`.`Id` = `hotels`.`CityId`)))
JOIN `hotel_clients`
ON ((`hotels`.`ID` = `hotel_clients`.`HotelId`)))
JOIN `airlines`
ON ((`airplane`.`AirlineName` = `airlines`.`Name`)));